### ISSUE TITLE
Add Pulsar: Lost Colony

### ISSUE THREAD

**Issue by Sch1nken** [arcataroger/awesome-engineering-games#10]
Heya, I'd like to suggest "Pulsar: Lost Colony" (https://store.steampowered.com/app/252870/PULSAR_Lost_Colony/) as "Ship Crews" (Space).

It's a mix of Bridge Crew, Barotrauma and FTL (imho).

**Comment by arcataroger** [comment]
Will add this momentarily. Thank you!
