### ISSUE TITLE
Add tags for Free to Play games?

### ISSUE THREAD

**Issue by ritog** [arcataroger/awesome-engineering-games#12]
There are some games on the list that are Free to Play (F2P).

I suggest that a tag be added to those games in the list which are F2P.

Let me know if you want a PR for the games that are currently on the list.

If you choose to go forward, we can discuss how to indicate F2P on the list. Should it be 🆓 emoji, or something else like `[F2P]`. We can discuss that later.

**Comment by arcataroger** [comment]
Thanks!  I added this in the latest version with the 🆓 tag as you suggested :)

Currently, only Bitburner has that tag. I manually checked the list, but please let me know if I missed any! (...really should add automation soon)

**Comment by ritog** [comment]
@arcataroger thanks! I will keep an eye out.
