### ISSUE TITLE
Add first person puzzle games

### ISSUE THREAD

**Issue by githubwoolf** [arcataroger/awesome-engineering-games#23]
Maybe we can add FP puzzle games as well, like:

- Antichamber
- Entropy Center
- Portal 
- Portal 2
- Quantum Conundrum
- Superliminal
- Viewfinder

**Comment by neuron-whisperer** [comment]
If this is accepted, I suggest some others:

* The Talos Principle (and its sequel)
* Colortone
* Manifold Garden
* The Unfinished Swan
* The Outer Wilds

**Comment by arcataroger** [comment]
While I love those games, I don't know if they really fall under "engineering" games...? The list is already quite long, and I hesitate to add too many more categories, especially big ones like "puzzle games". If there was some strong focus on engineering in those games, that's a different story, but is there?

What do you think?

There is a related discussion happening here: https://github.com/arcataroger/awesome-engineering-games/discussions/15

**Comment by githubwoolf** [comment]
Not more or less engineering than in the categories like Ship Crews or Puzzle & Casual – or games like Anno and Tropico, which do appear on the list. But I do understand your point, so I'm not going to fighing for it :)

**Comment by arcataroger** [comment]
I'm going to close this for now because there doesn't seem to be strong demand for it. Always happy to re-discuss this more in the future, though, if anyone wants to provide more feedback!

Thanks again for the suggestion, and sorry to turn it down for now.
